<?php
function componentizerV1RemoveHeaderFields($field){
  $header_fields_to_remove = [
    'field_5936e53e7c8ee',
    'field_5936e5927c8ef',
    'field_5970fd154b73e',
    'field_5970fd404b740',
    'field_59756bd10cb75',
  ];

  if ( !in_array($field['key'], $header_fields_to_remove) ){
    return $field;
  }

  $config = require(get_template_directory().'/includes/siteconfig.php');

  if ( stripos($config['header'], 'v1') === FALSE ){ //if we're not looking at v1 header, keep moving
    return $field;
  }
  return FALSE;
}
add_filter('acf/load_field','componentizerV1RemoveHeaderFields');


function componentizerAddV1Header(){
  $config = require(get_template_directory().'/includes/siteconfig.php');

  if ( stripos($config['header'], 'v1') === FALSE ){ //if we're not looking at v1 header, keep moving
    return;
  }

  if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
    	'key' => 'group_5ad798074b192',
    	'title' => 'Header Settings',
    	'fields' => array (
    		array (
    			'key' => 'field_5ad7b07d54a25',
    			'label' => 'General',
    			'name' => '',
    			'type' => 'tab',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'placement' => 'top',
    			'endpoint' => 0,
    		),
    		array (
    			'key' => 'field_5ad798dba798d',
    			'label' => 'Sticky?',
    			'name' => 'header_sticky',
    			'type' => 'true_false',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'message' => '',
    			'default_value' => 0,
    			'ui' => 1,
    			'ui_on_text' => '',
    			'ui_off_text' => '',
    		),
    		array (
    			'key' => 'field_5ad8777daf650',
    			'label' => 'Container Class',
    			'name' => 'header_container_class',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'placeholder' => '',
    			'prepend' => '',
    			'append' => '',
    			'maxlength' => '',
    		),
    		array (
    			'key' => 'field_5ad79a537aac3',
    			'label' => 'Background Color',
    			'name' => 'header_background_color',
    			'type' => 'color_picker',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '50',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => 'rgba(0,0,0,0)',
    		),
    		array (
    			'key' => 'field_5ad79a797aac4',
    			'label' => 'Scrolled Background Color',
    			'name' => 'header_scrolled_background_color',
    			'type' => 'color_picker',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => array (
    				array (
    					array (
    						'field' => 'field_5ad798dba798d',
    						'operator' => '==',
    						'value' => '1',
    					),
    				),
    			),
    			'wrapper' => array (
    				'width' => '50',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    		),
    		array (
    			'key' => 'field_5ad7b08c54a26',
    			'label' => 'Header Components',
    			'name' => '',
    			'type' => 'tab',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'placement' => 'top',
    			'endpoint' => 0,
    		),
    		array (
    			'key' => 'field_5ad7989ea798a',
    			'label' => 'Components',
    			'name' => 'header_components',
    			'type' => 'flexible_content',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'button_label' => 'Add Component',
    			'min' => '',
    			'max' => '',
    			'layouts' => array (
    				array (
    					'key' => '5ad798a31ff7c',
    					'name' => 'logo',
    					'label' => 'Logo',
    					'display' => 'block',
    					'sub_fields' => array (
    						array (
    							'key' => 'field_5ad798b6a798b',
    							'label' => 'Image',
    							'name' => 'image',
    							'type' => 'image',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '50%',
    								'class' => '',
    								'id' => '',
    							),
    							'return_format' => 'array',
    							'preview_size' => 'full',
    							'library' => 'all',
    							'min_width' => '',
    							'min_height' => '',
    							'min_size' => '',
    							'max_width' => '',
    							'max_height' => '',
    							'max_size' => '',
    							'mime_types' => '',
    						),
    						array (
    							'key' => 'field_5ad798faa798e',
    							'label' => 'Scrolled Image',
    							'name' => 'scrolled_image',
    							'type' => 'image',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => array (
    								array (
    									array (
    										'field' => 'field_5ad798dba798d',
    										'operator' => '==',
    										'value' => '1',
    									),
    								),
    							),
    							'wrapper' => array (
    								'width' => '50%',
    								'class' => '',
    								'id' => '',
    							),
    							'return_format' => 'array',
    							'preview_size' => 'full',
    							'library' => 'all',
    							'min_width' => '',
    							'min_height' => '',
    							'min_size' => '',
    							'max_width' => '',
    							'max_height' => '',
    							'max_size' => '',
    							'mime_types' => '',
    						),
    						array (
    							'key' => 'field_5ad79bc5c4d81',
    							'label' => 'Align',
    							'name' => 'align',
    							'type' => 'select',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'choices' => array (
    								'left' => 'Left',
    								'center' => 'Center',
    								'right' => 'Right',
    							),
    							'default_value' => array (
    								0 => 'left',
    							),
    							'allow_null' => 0,
    							'multiple' => 0,
    							'ui' => 0,
    							'ajax' => 0,
    							'return_format' => 'value',
    							'placeholder' => '',
    						),
    						array (
    							'key' => 'field_5ad798cca798c',
    							'label' => 'Container Class',
    							'name' => 'container_class',
    							'type' => 'text',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => 'col-md-2',
    							'placeholder' => '',
    							'prepend' => '',
    							'append' => '',
    							'maxlength' => '',
    						),
    					),
    					'min' => '',
    					'max' => '1',
    				),
    				array (
    					'key' => '5ad79952022e2',
    					'name' => 'nav',
    					'label' => 'Nav',
    					'display' => 'block',
    					'sub_fields' => array (
    						array (
    							'key' => 'field_5ad8843f15b3c',
    							'label' => 'Navigation Menu',
    							'name' => 'navigation_menu',
    							'type' => 'nav_menu',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '33',
    								'class' => '',
    								'id' => '',
    							),
    							'save_format' => 'id',
    							'container' => 'div',
    							'allow_null' => 0,
    						),
    						array (
    							'key' => 'field_5ad79bdcc4d82',
    							'label' => 'Align',
    							'name' => 'align',
    							'type' => 'select',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '33',
    								'class' => '',
    								'id' => '',
    							),
    							'choices' => array (
    								'left' => 'Left',
    								'center' => 'Center',
    								'right' => 'Right',
    							),
    							'default_value' => array (
    								0 => 'left',
    							),
    							'allow_null' => 0,
    							'multiple' => 0,
    							'ui' => 0,
    							'ajax' => 0,
    							'return_format' => 'value',
    							'placeholder' => '',
    						),
    						array (
    							'key' => 'field_5ad8849615b3d',
    							'label' => 'Container Class',
    							'name' => 'container_class',
    							'type' => 'text',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '33',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => 'col-md-8',
    							'placeholder' => '',
    							'prepend' => '',
    							'append' => '',
    							'maxlength' => '',
    						),
    					),
    					'min' => '',
    					'max' => '1',
    				),
    				array (
    					'key' => '5ad79962022e4',
    					'name' => 'ctas',
    					'label' => 'CTAs',
    					'display' => 'block',
    					'sub_fields' => array (
    						array (
    							'key' => 'field_5ad7996e022e6',
    							'label' => 'Buttons',
    							'name' => 'cta_btns',
    							'type' => 'clone',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '',
    								'class' => '',
    								'id' => '',
    							),
    							'clone' => array (
    								0 => 'field_594350be9d876',
    							),
    							'display' => 'seamless',
    							'layout' => 'block',
    							'prefix_label' => 0,
    							'prefix_name' => 1,
    						),
    						array (
    							'key' => 'field_5ad79bf6c4d83',
    							'label' => 'Align',
    							'name' => 'align',
    							'type' => 'select',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'choices' => array (
    								'left' => 'Left',
    								'center' => 'Center',
    								'right' => 'Right',
    							),
    							'default_value' => array (
    								0 => 'left',
    							),
    							'allow_null' => 0,
    							'multiple' => 0,
    							'ui' => 0,
    							'ajax' => 0,
    							'return_format' => 'value',
    							'placeholder' => '',
    						),
    						array (
    							'key' => 'field_5ad79969022e5',
    							'label' => 'Container Class',
    							'name' => 'container_class',
    							'type' => 'text',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '50',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => 'col-md-2',
    							'placeholder' => '',
    							'prepend' => '',
    							'append' => '',
    							'maxlength' => '',
    						),
    					),
    					'min' => '',
    					'max' => '1',
    				),
    				array (
    					'key' => '5ad877dbaf651',
    					'name' => 'custom_code',
    					'label' => 'Custom Code',
    					'display' => 'block',
    					'sub_fields' => array (
    						array (
    							'key' => 'field_5ad877e8af652',
    							'label' => 'Custom Code',
    							'name' => 'custom_code',
    							'type' => 'textarea',
    							'instructions' => '',
    							'required' => 0,
    							'conditional_logic' => 0,
    							'wrapper' => array (
    								'width' => '',
    								'class' => '',
    								'id' => '',
    							),
    							'default_value' => '',
    							'placeholder' => '',
    							'maxlength' => '',
    							'rows' => '',
    							'new_lines' => '',
    						),
    					),
    					'min' => '',
    					'max' => '',
    				),
    			),
    		),
    		array (
    			'key' => 'field_5ad7af566227f',
    			'label' => 'Mobile Options',
    			'name' => '',
    			'type' => 'tab',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'placement' => 'top',
    			'endpoint' => 0,
    		),
    		array (
    			'key' => 'field_5af4a054s78t4',
    			'label' => '',
    			'name' => '',
    			'type' => 'message',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '',
    				'class' => '',
    				'id' => '',
    			),
    			'message' => '<h3>Settings on this tab only apply to a website when viewed in a mobile browser.</h3>',
    			'new_lines' => '',
    			'esc_html' => 0,
    		),
    		array (
    			'key' => 'field_5adf654abb4fa',
    			'label' => 'Primary Logo (optional)',
    			'name' => 'header_mobile_header_logo',
    			'type' => 'image',
    			'instructions' => 'Fallback = Image in Header Components',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'return_format' => 'array',
    			'preview_size' => 'full',
    			'library' => 'all',
    			'min_width' => '',
    			'min_height' => '',
    			'min_size' => '',
    			'max_width' => '',
    			'max_height' => '',
    			'max_size' => '',
    			'mime_types' => '',
    		),
    		array (
    			'key' => 'field_5adf6563b6t27',
    			'label' => 'Scrolled Logo (optional)',
    			'name' => 'header_mobile_header_scrolled_logo',
    			'type' => 'image',
    			'instructions' => 'Fallback = Scrolled Image in Header Components',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'return_format' => 'array',
    			'preview_size' => 'full',
    			'library' => 'all',
    			'min_width' => '',
    			'min_height' => '',
    			'min_size' => '',
    			'max_width' => '',
    			'max_height' => '',
    			'max_size' => '',
    			'mime_types' => '',
    		),
    		array (
    			'key' => 'field_5adf6563bb4fb',
    			'label' => 'Menu Logo (optional)',
    			'name' => 'header_mobile_header_menu_logo',
    			'type' => 'image',
    			'instructions' => 'Appears on menu overlay, Fallback = Image in Header Components',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'return_format' => 'array',
    			'preview_size' => 'full',
    			'library' => 'all',
    			'min_width' => '',
    			'min_height' => '',
    			'min_size' => '',
    			'max_width' => '',
    			'max_height' => '',
    			'max_size' => '',
    			'mime_types' => '',
    		),
    		array (
    			'key' => 'field_5ad7af6d62280',
    			'label' => 'Logo Alignment',
    			'name' => 'header_mobile_logo_alignment',
    			'type' => 'select',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'choices' => array (
    				'left' => 'Left',
    				'center' => 'Center',
    				'right' => 'Right',
    			),
    			'default_value' => array (
    				0 => 'center',
    			),
    			'allow_null' => 0,
    			'multiple' => 0,
    			'ui' => 0,
    			'ajax' => 0,
    			'return_format' => 'value',
    			'placeholder' => '',
    		),
    		array (
    			'key' => 'field_5ad7afbd62282',
    			'label' => 'Menu Open Button Code',
    			'name' => 'header_mobile_menu_expand_button',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'placeholder' => 'Defaults to <i class="fa fa-bars"></i>',
    			'prepend' => '',
    			'append' => '',
    			'maxlength' => '',
    		),
    		array (
    			'key' => 'field_5af5c642d2433',
    			'label' => 'Menu Close Button Code',
    			'name' => 'header_mobile_menu_close_button_code',
    			'type' => 'text',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'default_value' => '',
    			'placeholder' => 'Defaults to <i class="fa fa-times"></i>',
    			'prepend' => '',
    			'append' => '',
    			'maxlength' => '',
    		),
    		array (
    			'key' => 'field_5ad7af9162281',
    			'label' => 'Menu Open/Close Button Alignment',
    			'name' => 'header_mobile_menu_expand_contract_alignment',
    			'type' => 'select',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'choices' => array (
    				'left' => 'Left',
    				'center' => 'Center',
    				'right' => 'Right',
    			),
    			'default_value' => array (
    				0 => 'right',
    			),
    			'allow_null' => 0,
    			'multiple' => 0,
    			'ui' => 0,
    			'ajax' => 0,
    			'return_format' => 'value',
    			'placeholder' => '',
    		),
    		array (
    			'key' => 'field_5ad7b01462283',
    			'label' => 'Menu Animation',
    			'name' => 'header_mobile_menu_animation',
    			'type' => 'select',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'choices' => array (
    				'slide-down' => 'Slide Down',
    				'slide-from-right' => 'Slide From Right',
    				'slide-from-left' => 'Slide From Left',
    			),
    			'default_value' => array (
    				0 => 'Slide Down',
    			),
    			'allow_null' => 0,
    			'multiple' => 0,
    			'ui' => 0,
    			'ajax' => 0,
    			'return_format' => 'value',
    			'placeholder' => '',
    		),
    		array (
    			'key' => 'field_5ad967820206e',
    			'label' => 'CTA Button Position',
    			'name' => 'header_mobile_cta_button_position',
    			'type' => 'select',
    			'instructions' => '',
    			'required' => 0,
    			'conditional_logic' => 0,
    			'wrapper' => array (
    				'width' => '33',
    				'class' => '',
    				'id' => '',
    			),
    			'choices' => array (
    				'in-menu' => 'Visible Inside The Menu',
    				'always-shown' => 'Always Visible',
    			),
    			'default_value' => array (
    			),
    			'allow_null' => 0,
    			'multiple' => 0,
    			'ui' => 0,
    			'ajax' => 0,
    			'return_format' => 'value',
    			'placeholder' => '',
    		),
    	),
    	'location' => array (
    		array (
    			array (
    				'param' => 'options_page',
    				'operator' => '==',
    				'value' => 'theme-general-settings',
    			),
    		),
    	),
    	'menu_order' => 0,
    	'position' => 'normal',
    	'style' => 'default',
    	'label_placement' => 'top',
    	'instruction_placement' => 'label',
    	'hide_on_screen' => '',
    	'active' => 1,
    	'description' => '',
    	'modified' => 1526057239,
    ));

    endif;
}
add_filter('acf/init','componentizerAddV1Header');
